# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  postgresql:
    service:
      port: "5432"
    auth:
      database: "ecommerce"
      username: "ecommerce_admin"
      password: "ecommerce_admin"

app:
  replicaCount: "2"

  image:
    frontend:
      repository: "kng1259/ecommerce-frontend"
      tag: "latest"
    backend:
      repository: "kng1259/ecommerce-backend"
      tag: "latest"
    pullPolicy: "IfNotPresent"
    # tag: "0.37.5"
    pullSecrets: []

  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

  google:
    clientId: "your-google-client-id"
    clientSecret: "your-google-client-secret"
    redirectUri: "http://localhost:8003/api/auth/google/callback"

  ghtk:
    baseUrl: "https://services-staging.ghtklab.com/services"
    token: "your-ghtk-token"
    partnerCode: "your-ghtk-partner-code"

  momo:
    accessKey: "your-momo-access-key"
    secretKey: "your-momo-secret-key"
    partnerCode: "your-momo-partner-code"
    endPoint: "https://test-payment.momo.vn/v2/gateway/api/create"
    ipnUrl: "http://your-domain.com/api/payment/callback"
    redirectUrl: "http://your-redirect-url.com"

  s3:
    publicUrl: http://localhost:9000
    region: "ap-southeast-1"
    bucketName: "images-ecommerce"
    accessKey: "admin"
    secretKey: "admin123"

postgresql:
  enabled: "true"
  networkPolicy:
    enabled: "false"
  resourcesPreset: "small"

minio:
  enabled: "true"
  image:
    repository: bitnamilegacy/minio
  console:
    image:
      repository: bitnamilegacy/minio-object-browser
  auth:
    rootUser: "admin"
    rootPassword: "admin123"

  defaultBuckets: "images-ecommerce"
# garage:
#   enabled: "true"
#   garage:
#     replicationFactor: "2"
#     s3:
#       api:
#         region: "ap-southeast-1"

#   deployement:
#     replicas: 1

#   persistence:
#     enabled: true
#     meta:
#       storageClass: "standard"
#       size: "500Mi"
#     data:
#       storageClass: "standard"
#       size: "5Gi"
