version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ecommerce_service:
    image: kng1259/ecommerce-backend:latest
    container_name: ecommerce_service
    # restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8003:8003"
    env_file:
      - .env
    environment:
      DATABASE_HOST: postgres
      S3_HOST: http://minio:9000

  ecommerce_frontend:
    image: kng1259/ecommerce-frontend:latest
    container_name: ecommerce_frontend
    restart: always
    depends_on:
      ecommerce_service:
        condition: service_started
    ports:
      - "3000:3000"

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-admin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-admin123}
      MINIO_DOMAIN: "localhost"
      MINIO_SITE_REGION: "ap-southeast-1"
      MINIO_SITE_NAME: "docker-minio"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mc_client:
    image: minio/mc:latest
    container_name: mc_client
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 ${S3_ACCESS_KEY:-admin} ${S3_SECRET_KEY:-admin123};
      /usr/bin/mc mb myminio/${S3_BUCKET_NAME:-images-ecommerce} --ignore-existing;
      /usr/bin/mc anonymous set public myminio/${S3_BUCKET_NAME:-images-ecommerce};
      exit 0
      "

  # garage:
  #   image: dxflrs/garage:v2.1.0
  #   container_name: garage
  #   restart: always
  #   ports:
  #     - 3900:3900
  #     - 3901:3901
  #     - 3902:3902
  #   volumes:
  #     - ./garage/garage.toml:/etc/garage.toml
  #     - garage_metadata:/var/lib/garage/meta
  #     - garage_data:/var/lib/garage/data

  # garage-webui:
  #   image: khairul169/garage-webui:latest
  #   container_name: garage-webui
  #   restart: always
  #   volumes:
  #     - ./garage/garage.toml:/etc/garage.toml:ro
  #   ports:
  #     - 3909:3909
  #   environment:
  #     API_BASE_URL: "http://garage:3903"
  #     S3_ENDPOINT_URL: "http://garage:3900"

volumes:
  postgres_data:
  minio_data:
  # garage_metadata:
  # garage_data:
