server:
  port: ${SERVER_PORT}

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG


ghtk:
  api:
    base-url: ${GHTK_BASE_URL}
    token: ${GHTK_TOKEN}
    ghtk-partner-code: ${GHTK_PARTNER_CODE}

momo:
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  partner-code: ${PARTNER_CODE}
  endpoint: ${END_POINT}
  query-endpoint: ${QUERY_ENDPOINT}
  ipn-url: ${IPN_URL}
  momo-redirect-url: ${MOMO_REDIRECT_URL}

spring:
  application:
    name: ${SPRING_APP_NAME}
    home-url: ${HOME_URL}
    error-valid-user-url: ${ERROR_VALID_USER_URL}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            expiration-time: ${GOOGLE_EXPIRATION_TIME}

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    show-sql: ${SHOW_SQL}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
