apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-svc
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    tier: backend
spec:
  type: ClusterIP
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    tier: backend
  ports:
    - port: 8003
      targetPort: 8003

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-svc
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    tier: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    tier: frontend
  ports:
    - port: 3000
      targetPort: 3000